config/routes.rb
Students::Application.routes.draw do
  resources :courses do
    member do
      get :roll
    end
  end

  resources :awards

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end

  end

end

app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :name, :student_id, :year

  belongs_to :student
  validates_existence_of :student, :both => false
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = Award.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = Award.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = Award.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = Award.new(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = Award.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = Award.find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to awards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.select :student_id, Student.find(:all, :order => "family_name,
    given_name").collect {|s|
      [s.name, s.id]} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<h1>Listing awards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Student</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @awards.each do |award| %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.year %></td>
    <td><%= award.student.name %></td>
    

    <td><%= link_to 'Show', award %></td>
    <td><%= link_to 'Edit', edit_award_path(award) %></td>
    <td><%= link_to 'Destroy', award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Award', new_award_path %>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @award.name %>
</p>

<p>
  <b>Year:</b>
  <%= @award.year %>
</p>

<p>
  <b>Student:</b>
  <%= @award.student.name %>
  
</p>


<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>